# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import msgid_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='base.proto',
  package='tbsproto',
  serialized_pb=_b('\n\nbase.proto\x12\x08tbsproto\x1a\x0bmsgid.proto\"&\n\x08KeyValue\x12\x0b\n\x03Key\x18\x01 \x02(\t\x12\r\n\x05Value\x18\x02 \x02(\t\"6\n\x0e\x45xtensionsData\x12$\n\x08\x45lements\x18\x01 \x03(\x0b\x32\x12.tbsproto.KeyValue\"l\n\tBaseError\x12\x0f\n\x04\x43ode\x18\x01 \x02(\x03:\x01\x30\x12\x0f\n\x07Message\x18\x02 \x01(\t\x12\x0e\n\x06Source\x18\x03 \x01(\t\x12-\n\nExtensions\x18\xe8\x07 \x01(\x0b\x32\x18.tbsproto.ExtensionsData\"\x9e\x01\n\x08\x42\x61seHead\x12\r\n\x05ReqID\x18\x01 \x02(\x04\x12\x0c\n\x04Time\x18\x02 \x01(\x03\x12\"\n\x05MsgID\x18\x03 \x01(\x0e\x32\x13.tbsproto.EnumMsgID\x12\"\n\x05\x45rror\x18\x04 \x01(\x0b\x32\x13.tbsproto.BaseError\x12-\n\nExtensions\x18\xe8\x07 \x01(\x0b\x32\x18.tbsproto.ExtensionsData\"J\n\x08\x42\x61seBody\x12\x0f\n\x07MsgData\x18\x01 \x01(\x0c\x12-\n\nExtensions\x18\xe8\x07 \x01(\x0b\x32\x18.tbsproto.ExtensionsData\"M\n\x07\x42\x61seMsg\x12 \n\x04Head\x18\x01 \x02(\x0b\x32\x12.tbsproto.BaseHead\x12 \n\x04\x42ody\x18\x02 \x01(\x0b\x32\x12.tbsproto.BaseBodyB7\n\x1e\x63om.thebeastshop.monitor.protoB\x15TheBeastShopBaseProto')
  ,
  dependencies=[msgid_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_KEYVALUE = _descriptor.Descriptor(
  name='KeyValue',
  full_name='tbsproto.KeyValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Key', full_name='tbsproto.KeyValue.Key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Value', full_name='tbsproto.KeyValue.Value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=75,
)


_EXTENSIONSDATA = _descriptor.Descriptor(
  name='ExtensionsData',
  full_name='tbsproto.ExtensionsData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Elements', full_name='tbsproto.ExtensionsData.Elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=131,
)


_BASEERROR = _descriptor.Descriptor(
  name='BaseError',
  full_name='tbsproto.BaseError',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Code', full_name='tbsproto.BaseError.Code', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Message', full_name='tbsproto.BaseError.Message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Source', full_name='tbsproto.BaseError.Source', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Extensions', full_name='tbsproto.BaseError.Extensions', index=3,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=133,
  serialized_end=241,
)


_BASEHEAD = _descriptor.Descriptor(
  name='BaseHead',
  full_name='tbsproto.BaseHead',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ReqID', full_name='tbsproto.BaseHead.ReqID', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Time', full_name='tbsproto.BaseHead.Time', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='MsgID', full_name='tbsproto.BaseHead.MsgID', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Error', full_name='tbsproto.BaseHead.Error', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Extensions', full_name='tbsproto.BaseHead.Extensions', index=4,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=244,
  serialized_end=402,
)


_BASEBODY = _descriptor.Descriptor(
  name='BaseBody',
  full_name='tbsproto.BaseBody',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='MsgData', full_name='tbsproto.BaseBody.MsgData', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Extensions', full_name='tbsproto.BaseBody.Extensions', index=1,
      number=1000, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=404,
  serialized_end=478,
)


_BASEMSG = _descriptor.Descriptor(
  name='BaseMsg',
  full_name='tbsproto.BaseMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Head', full_name='tbsproto.BaseMsg.Head', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Body', full_name='tbsproto.BaseMsg.Body', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=480,
  serialized_end=557,
)

_EXTENSIONSDATA.fields_by_name['Elements'].message_type = _KEYVALUE
_BASEERROR.fields_by_name['Extensions'].message_type = _EXTENSIONSDATA
_BASEHEAD.fields_by_name['MsgID'].enum_type = msgid_pb2._ENUMMSGID
_BASEHEAD.fields_by_name['Error'].message_type = _BASEERROR
_BASEHEAD.fields_by_name['Extensions'].message_type = _EXTENSIONSDATA
_BASEBODY.fields_by_name['Extensions'].message_type = _EXTENSIONSDATA
_BASEMSG.fields_by_name['Head'].message_type = _BASEHEAD
_BASEMSG.fields_by_name['Body'].message_type = _BASEBODY
DESCRIPTOR.message_types_by_name['KeyValue'] = _KEYVALUE
DESCRIPTOR.message_types_by_name['ExtensionsData'] = _EXTENSIONSDATA
DESCRIPTOR.message_types_by_name['BaseError'] = _BASEERROR
DESCRIPTOR.message_types_by_name['BaseHead'] = _BASEHEAD
DESCRIPTOR.message_types_by_name['BaseBody'] = _BASEBODY
DESCRIPTOR.message_types_by_name['BaseMsg'] = _BASEMSG

KeyValue = _reflection.GeneratedProtocolMessageType('KeyValue', (_message.Message,), dict(
  DESCRIPTOR = _KEYVALUE,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.KeyValue)
  ))
_sym_db.RegisterMessage(KeyValue)

ExtensionsData = _reflection.GeneratedProtocolMessageType('ExtensionsData', (_message.Message,), dict(
  DESCRIPTOR = _EXTENSIONSDATA,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.ExtensionsData)
  ))
_sym_db.RegisterMessage(ExtensionsData)

BaseError = _reflection.GeneratedProtocolMessageType('BaseError', (_message.Message,), dict(
  DESCRIPTOR = _BASEERROR,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.BaseError)
  ))
_sym_db.RegisterMessage(BaseError)

BaseHead = _reflection.GeneratedProtocolMessageType('BaseHead', (_message.Message,), dict(
  DESCRIPTOR = _BASEHEAD,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.BaseHead)
  ))
_sym_db.RegisterMessage(BaseHead)

BaseBody = _reflection.GeneratedProtocolMessageType('BaseBody', (_message.Message,), dict(
  DESCRIPTOR = _BASEBODY,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.BaseBody)
  ))
_sym_db.RegisterMessage(BaseBody)

BaseMsg = _reflection.GeneratedProtocolMessageType('BaseMsg', (_message.Message,), dict(
  DESCRIPTOR = _BASEMSG,
  __module__ = 'base_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.BaseMsg)
  ))
_sym_db.RegisterMessage(BaseMsg)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.thebeastshop.monitor.protoB\025TheBeastShopBaseProto'))
# @@protoc_insertion_point(module_scope)
