# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: quote.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='quote.proto',
  package='tbsproto',
  serialized_pb=_b('\n\x0bquote.proto\x12\x08tbsproto\"V\n\tQuoteTick\x12\n\n\x02ID\x18\x01 \x03(\x04\x12\x0c\n\x04Time\x18\x02 \x03(\x03\x12\r\n\x05Price\x18\x03 \x03(\x01\x12\x0e\n\x06Volume\x18\x04 \x03(\x03\x12\x10\n\x08property\x18\x05 \x03(\x03\"\'\n\tQuoteData\x12\x0b\n\x03Obj\x18\x01 \x02(\t\x12\r\n\x05\x44ynas\x18\x03 \x02(\x03\x42\x34\n\x1e\x63om.thebeastshop.monitor.protoB\x12TheBeastQuoteProto')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_QUOTETICK = _descriptor.Descriptor(
  name='QuoteTick',
  full_name='tbsproto.QuoteTick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ID', full_name='tbsproto.QuoteTick.ID', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Time', full_name='tbsproto.QuoteTick.Time', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Price', full_name='tbsproto.QuoteTick.Price', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Volume', full_name='tbsproto.QuoteTick.Volume', index=3,
      number=4, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='property', full_name='tbsproto.QuoteTick.property', index=4,
      number=5, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=111,
)


_QUOTEDATA = _descriptor.Descriptor(
  name='QuoteData',
  full_name='tbsproto.QuoteData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Obj', full_name='tbsproto.QuoteData.Obj', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Dynas', full_name='tbsproto.QuoteData.Dynas', index=1,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=152,
)

DESCRIPTOR.message_types_by_name['QuoteTick'] = _QUOTETICK
DESCRIPTOR.message_types_by_name['QuoteData'] = _QUOTEDATA

QuoteTick = _reflection.GeneratedProtocolMessageType('QuoteTick', (_message.Message,), dict(
  DESCRIPTOR = _QUOTETICK,
  __module__ = 'quote_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.QuoteTick)
  ))
_sym_db.RegisterMessage(QuoteTick)

QuoteData = _reflection.GeneratedProtocolMessageType('QuoteData', (_message.Message,), dict(
  DESCRIPTOR = _QUOTEDATA,
  __module__ = 'quote_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.QuoteData)
  ))
_sym_db.RegisterMessage(QuoteData)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.thebeastshop.monitor.protoB\022TheBeastQuoteProto'))
# @@protoc_insertion_point(module_scope)
