# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import quote_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service.proto',
  package='tbsproto',
  serialized_pb=_b('\n\rservice.proto\x12\x08tbsproto\x1a\x0bquote.proto\"h\n\x07Request\x12&\n\x07Service\x18\x01 \x02(\x0e\x32\x15.tbsproto.ServiceType\x12\'\n\x03Sub\x18\x02 \x02(\x0e\x32\x11.tbsproto.SubType:\x07SubNone\x12\x0c\n\x04Objs\x18\x03 \x03(\t\"}\n\x08Response\x12&\n\x06Result\x18\x01 \x02(\x0e\x32\x16.tbsproto.ServiceError\x12&\n\x07Service\x18\x02 \x02(\x0e\x32\x15.tbsproto.ServiceType\x12!\n\x04\x44\x61ta\x18\x04 \x02(\x0b\x32\x13.tbsproto.QuoteData*\x1e\n\x0bServiceType\x12\x0f\n\x0bServiceDyna\x10\x01*-\n\x07SubType\x12\x0b\n\x07SubNone\x10\x01\x12\t\n\x05SubOn\x10\x02\x12\n\n\x06SubOff\x10\x03*\xa7\x01\n\nPeriodType\x12\x08\n\x04Min1\x10\x01\x12\x08\n\x04Min5\x10\x02\x12\t\n\x05Min10\x10\x03\x12\t\n\x05Min30\x10\x04\x12\t\n\x05Min60\x10\x05\x12\n\n\x06Min120\x10\x06\x12\n\n\x06Min180\x10\x07\x12\n\n\x06Min240\x10\x08\x12\x07\n\x03\x44\x61y\x10\t\x12\x08\n\x04Week\x10\n\x12\t\n\x05Month\x10\x0b\x12\n\n\x06Season\x10\x0c\x12\x0c\n\x08HalfYear\x10\r\x12\x08\n\x04Year\x10\x0e*J\n\x0cServiceError\x12\x10\n\x0c\x45rrServiceOK\x10\x00\x12\x14\n\x0f\x45rrServiceBegin\x10\xd1\x0f\x12\x12\n\rErrServiceEnd\x10\xb8\x17\x42:\n\x1e\x63om.thebeastshop.monitor.protoB\x18TheBeastShopServiceProto')
  ,
  dependencies=[quote_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_SERVICETYPE = _descriptor.EnumDescriptor(
  name='ServiceType',
  full_name='tbsproto.ServiceType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ServiceDyna', index=0, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=273,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_SERVICETYPE)

ServiceType = enum_type_wrapper.EnumTypeWrapper(_SERVICETYPE)
_SUBTYPE = _descriptor.EnumDescriptor(
  name='SubType',
  full_name='tbsproto.SubType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SubNone', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SubOn', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SubOff', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=305,
  serialized_end=350,
)
_sym_db.RegisterEnumDescriptor(_SUBTYPE)

SubType = enum_type_wrapper.EnumTypeWrapper(_SUBTYPE)
_PERIODTYPE = _descriptor.EnumDescriptor(
  name='PeriodType',
  full_name='tbsproto.PeriodType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Min1', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min5', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min10', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min30', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min60', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min120', index=5, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min180', index=6, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Min240', index=7, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Day', index=8, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Week', index=9, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Month', index=10, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Season', index=11, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HalfYear', index=12, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Year', index=13, number=14,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=353,
  serialized_end=520,
)
_sym_db.RegisterEnumDescriptor(_PERIODTYPE)

PeriodType = enum_type_wrapper.EnumTypeWrapper(_PERIODTYPE)
_SERVICEERROR = _descriptor.EnumDescriptor(
  name='ServiceError',
  full_name='tbsproto.ServiceError',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ErrServiceOK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ErrServiceBegin', index=1, number=2001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ErrServiceEnd', index=2, number=3000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=522,
  serialized_end=596,
)
_sym_db.RegisterEnumDescriptor(_SERVICEERROR)

ServiceError = enum_type_wrapper.EnumTypeWrapper(_SERVICEERROR)
ServiceDyna = 1
SubNone = 1
SubOn = 2
SubOff = 3
Min1 = 1
Min5 = 2
Min10 = 3
Min30 = 4
Min60 = 5
Min120 = 6
Min180 = 7
Min240 = 8
Day = 9
Week = 10
Month = 11
Season = 12
HalfYear = 13
Year = 14
ErrServiceOK = 0
ErrServiceBegin = 2001
ErrServiceEnd = 3000



_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='tbsproto.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Service', full_name='tbsproto.Request.Service', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Sub', full_name='tbsproto.Request.Sub', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Objs', full_name='tbsproto.Request.Objs', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=144,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='tbsproto.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Result', full_name='tbsproto.Response.Result', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Service', full_name='tbsproto.Response.Service', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Data', full_name='tbsproto.Response.Data', index=2,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=271,
)

_REQUEST.fields_by_name['Service'].enum_type = _SERVICETYPE
_REQUEST.fields_by_name['Sub'].enum_type = _SUBTYPE
_RESPONSE.fields_by_name['Result'].enum_type = _SERVICEERROR
_RESPONSE.fields_by_name['Service'].enum_type = _SERVICETYPE
_RESPONSE.fields_by_name['Data'].message_type = quote_pb2._QUOTEDATA
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.enum_types_by_name['ServiceType'] = _SERVICETYPE
DESCRIPTOR.enum_types_by_name['SubType'] = _SUBTYPE
DESCRIPTOR.enum_types_by_name['PeriodType'] = _PERIODTYPE
DESCRIPTOR.enum_types_by_name['ServiceError'] = _SERVICEERROR

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), dict(
  DESCRIPTOR = _REQUEST,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.Request)
  ))
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), dict(
  DESCRIPTOR = _RESPONSE,
  __module__ = 'service_pb2'
  # @@protoc_insertion_point(class_scope:tbsproto.Response)
  ))
_sym_db.RegisterMessage(Response)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\036com.thebeastshop.monitor.protoB\030TheBeastShopServiceProto'))
# @@protoc_insertion_point(module_scope)
